### ISSUE TITLE
反馈一下我遇到的问题

### ISSUE THREAD

**Issue by hunaulys** [OneBST/GGanalysislib#4]
命令行界面运行”python3 -m pip install numpy matplotlib“没有反应，将python3改成python后就有反应，不知道有什么区别。运行draw_img.py没有反应，过一会出现“Process finished with exit code 0”，中间啥也没看到。只成功运行了example.py，还是不会用您的这个工具

**Comment by OneBST** [comment]
python3和python都是调用python的方式，win下面只有一种python的话就用python就行，linux下面大部分时候是python3。你安装上了就行。
运行draw_img.py是画图的，能成功运行就会在fig文件夹下面生成图片，说明这个包正常工作了。
如果想看怎么用，可以抄https://bbs.nga.cn/read.php?tid=28216360里面示例的代码。

**Comment by hunaulys** [comment]
感谢
