### ISSUE TITLE
要怎麼計算像是「非小酋」網站上透過過去運氣分析幾抽後會出金？

### ISSUE THREAD

**Issue by seriaati** [OneBST/GGanalysislib#6]
個人覺得計算出抽到的概率對大部分使用者來說沒有太大的參考意義。
有沒有辦法算出幾抽後會抽到呢？

**Comment by OneBST** [comment]
只能计算出在当前情况下的分布，非小酋给出的预计几抽后出金是把这个分布的峰值部分给你提了出来
随机的东西怎么可能肯定几抽之后出，毕竟也不能预知接下来的彩票号码不是吗

**Comment by seriaati** [comment]
是的，我可以理解，所以目前這個lib只能根據給的情況算出分佈，沒有辦法取峰值嗎

**Comment by OneBST** [comment]
都算出分布了，你取里面最大的地方不就行了吗，扫一遍分布就行了啊

**Comment by seriaati** [comment]
不好意思...我剛接觸這方面的東西
能否請大佬向我說明一下具體要怎麼操作？

**Comment by OneBST** [comment]
啊这，你1/4概率在第一抽出，1/2概率在第二抽出，1/4概率在第三抽出，峰值就是比哪个位置最大啊

**Comment by seriaati** [comment]
懂了，謝謝。
